### ISSUE TITLE
Video multi camera support.

### ISSUE THREAD

**Issue by htcohio** [DroneBridge/DroneBridge#14]
Hello, I'm relatively new to Wifibroadcast but I've been heavily involved in the rcgroups Forum, I believe in the project and I have learned a lot so far however, I'm not exactly sure how to utilize github if I have something to add so I apologize if this is not the correct spot.

I picked up an Arducam multi-camera splitter and worked with User1321 from rcgroups who was able to remotely write code so that the video Switcher could be assigned to any RC Channel (1-8). The air RPI monitors the mavlink channel value.

Video switcher module
http://www.arducam.com/multi-camera-adapter-module-raspberry-pi/

At first it only works with USB as a second link but the other day he was able to integrate it with the standard telemetry connection with pixhawk.

There do not appear to be any issues and works flawlessly.  An image has been created and a link to my Google Drive is below.  Would it be possible to integrate that portion of the code to drone Bridge?

Configuration is simply set at the bottom of Wifibroadcast.txt file i e pwm value for Associated Channel as well as how many cameras you want to have on the craft.

Here is a link to a video demonstrating the video switcher.
https://youtu.be/swry3rPmeis

Please let me know if you have any questions or suggestions.

Cheers,

Justin (Htcohio)

Image
https://drive.google.com/file/d/1vHvJlccpbVlma0mXGT332akWsoPuuQH3/view?usp=drivesdk

**Comment by careyer** [comment]
This is awesome! However, this solution occupies one of the already very limited 8 MavLink channels. It would make a whole lot of sense to expand the 8 proportiol channels (MavLink) with a number of additional switching channels (e.g CH9-12 maybe even CH9-16) which can either control GPIOs (On-Off) or can be interpreted in the WBC-loop to trigger additions in the code (e.g. switch between different OSD screens, trigger a python script, switch multiple cameras etc...) The benefit of this would be unlimited. Right now the only limitation of EZ-WBC is the 8Ch limitation which results from the MavLink override channels mimik. It would be awesome if someone could overcome this by sending more channels to the air which do not nessesary need to be mavlink channels.

**Comment by user1321** [comment]
Hi!
Maybe I am wrong in something, please correct me in that case.
>>However, this solution occupies one of the already very limited 8 MavLink channels.
That`s true it case if we receive data via wifi dongle at Air side.
Something like: WifiDongle -> RPi Air -> Pixhawk -> :
mavlink_msg_rc_channels_override_get_chan8_raw  (1 - 8)
But, in case of "image" above data "arrive" not from wifi, but:
PPM receiver -> Pixhawk-> RPi Air.
I did some test`s and it look like we can use more then 8 channels. 
![chan](https://user-images.githubusercontent.com/33780612/42124892-518694a4-7c74-11e8-9a51-918dcc68df82.jpeg)

**Comment by careyer** [comment]
@user1321: Sorry I did not make myself clear enough. When using RC=mavlink only 8Ch can right now be transfered to the drone. This is a limitation of the mavlink Protocol or to be precise of the mavlink_rc_channels override: i.e when using Mavlink for RC control no more than 8Ch on the copter side of things can be used which is a pain.  The GroundStation can read more than 8 channels for sure but they do not get transmitted to the drone. I am not sure how this behaves for SUMD and the other possible protocols but I think they are also limited to 8Ch as of now. (Even though there is no reason for it since these protocols natively support >8Ch).

**Comment by careyer** [comment]
Here goes an example why 8Chs on a Ardupilot Quad can get easily insufficient:
Ch1 = Nick
Ch2 = Roll
Ch3 = Thr
Ch4 = Yaw
Ch5 = Flight Mode
Ch7 = Gimbal Nick
Ch8 = Gimbal Roll

Ch9 = Camera Switcher
Ch10 = Landing Gear
Ch11 = Lights
Ch12 = Drop Servo
Ch13 = ...

**Comment by user1321** [comment]
>>When using RC=mavlink only 8Ch can right now
I assume you use "Ground RPi" to connect joystick and transferring it`s data to "Air RPi".
Is it correct?
If so, then you have "two-way" data link between Air RPi <-> Ground RPi.
_______________________________________________
Data transmission can be simple as:
Ground to Air link send: echo "test msg" |  tx_rawsock -p ....
Ground to Air receive:  rx -p .... |  stdin_myprog_name
And at "Air Side" vice versa

But that in case if you use "Ground RPi" as transmitter, not only receiver.
______________________________________________

Idea of "image" above was to use RC Joystick transmitter(!) to send data. Since RC transmitter is usually more powerful than wifi card at ground station.
And here is a difference.

**Comment by careyer** [comment]
@user1321 : You are right. I am using WBC in  a two-way (bi-directional) mode, i.e:  Videodownlink + Telemetry Up+Downlink + RC Uplink. I only wnat to have one single RF-link to rule it all since multiple RF-links interfere with each other (more or less).

It has been proved that RC-Uplink via WBC can by far outperform a regular RC-transmitter/receiver combo (like e.g. FrSky). Ranges of >14km have been achived with WBC RC-control. This is due to the fact that for uplink a much smaller bitrate is used which greatly improves WiFi range.

**Comment by htcohio** [comment]
Correct me if I'm wrong, but as it stands the "Air RPI" Reed's Channel data from the FC so in theory shouldn't work with a USB joystick through wfbc or an LRS RC system?

**Comment by htcohio** [comment]
Hey guys,

I know very little about the pixhawk cube with Edison board. I believe it's still pretty new... I know that the goal of this FCC was to have a built-in companion computer I'm not sure how it Stacks up against any of the rpi's however I was watching this video and noticed that it has a breakout connector for USB and PWM.  If this is the case, it sounds like you could simply assign a switch for cameras or any other device to any channel and connect it directly to the companion computer.

Have any of you worked with the pixhawk 2 and Edison board at all?

**Comment by careyer** [comment]
@htcohio : 
The situation is as follows:
- USB Joystick (or Taranis in USB-Joystick mode) connected to GroundPI
- configuration: RC=mavlink
- GroundPi reads input from joystick and creates appropriate Mavlink RC Override packages (only 8ch supported due to restrictions of the MavLink protocol)
- AirPi receives the RC-control inputs together with the rest of the MavLink Data
- AirPi is connected to FC via Serial and feeds that data to the FC.
- i.e: you need no regular RC-transmitter/receiver at all to control your aircraft. only the limitation to 8Ch sucks!

**Comment by htcohio** [comment]
Completely understand what you're saying.  It would be very convenient and you could probably 3D print an entire RC transmitter enclosure which contained the RPI ground and antennas similar to the DJI system.

I have a dragonlink UHF system and I can tell you that although the range in Wi-Fi broadcast telemetry is impressive but probably does not have the 50 km capability of UHF.

I personally like having a completely separate Telemetry stream with the dragonlink as a safeguard in the event wfbc fails. 

So from my point of view, Channel 1-8 can be dedicated for all components tied to the rpi air and anything else controlled by pwm/sbus on channels 9-xx can be independent.

In order to have a portable solution I thought about the possibility of mounting the RPI ground to the back of Taranis RC transmitter and encasing it somehow which would still result in a somewhat portable solution.  

Now, anybody coming from the world of 2. 4 control only would probably want to pursue full control through wfbc to avoid the need for a separate UHF system.  It would certainly be more efficient..  

Mavlink in general seems to have so many small limitations that can be frustrating sometimes.  Maybe the people over at ardupilot can come up with a better solution in the future However, I am not a programmer so I really can't say much.

**Comment by user1321** [comment]
@careyer
> Ch9 = Camera Switcher
Ch10 = Landing Gear
Ch11 = Lights
Ch12 = Drop Servo
Ch13 = switchable IR-Filter
CH14 = ...


All the things from ch9 to ch 13 are bool type or maybe 1,2,3 (but not 0-1023 ).
Why you don`t want to use something like I posted at post 6?
You can easily send data from ground station calling  tx_rawsock -p .... and passing some input to it.
for example: echo "Lights" |  tx_rawsock -p ....
At Air Side: tx_rawsock -p .... | pass value to some script.py?

> If so, then you have "two-way" data link between Air RPi <-> Ground RPi.
Data transmission can be simple as:
Ground to Air link send: echo "test msg" | tx_rawsock -p ....
Ground to Air receive: rx -p .... | stdin_myprog_name

**Comment by careyer** [comment]
@htcohio : Perfect. You got my idea =) Use Ch1-Ch8 for Mavlink enabled FC... use Ch9... xx independently for something else! I already realized what you described above:
<img src="http://www.ip-networx.de/content/GitHub/Taranis_EZWBC_1.jpg"> ... <img src="http://www.ip-networx.de/content/GitHub/Taranis_EZWBC_2.jpg">

<img src="http://www.ip-networx.de/content/GitHub/Taranis_EZWBC_3.jpg">

**Comment by careyer** [comment]
Exactly! This would be the ultimate solution in terms of interoperability. However it seems to be quite tricky to realize SBUS on the RPi since it has no hardware timer. But it is doable. If it turns out not to be possible boolean extra channels would be the 2nd best solution. At the end of the day everthing is better than being stuck on 8 Channels only.

**Comment by seeul8er** [comment]
Hi guys!
**DroneBridge can do 12ch RC with MSP & SUMD output on the UAV side.** SUMD is tested and supported by almost all FC platforms, including Pixracer. DroneBridge RC currently only supports TGYi6s since I do not have access to any other hardware, but it is super easy to write code/drivers for any other RC. If you are interested I can help you out with some examples! It mainly involves copy/paste plus some button mapping!
If you want to use some RC channels for other things rather than forwarding them to the FC you can modify the control module on the UAV side. The code is documented so it should not be a big issue.

I do not want to include any problem specific solutions in the project. Parsing the telemetry output seems to work well for you but it is not "clean" enough for me (too much hacking/messing around with the telemetry stream involved etc.).
DroneBridge features a communication protocol/module that is specifically designed to handle that kind of messages. I will think about adding a camera switcher to it. The switch could be triggered from the app. I might allow repurposing some of the DroneBridge RC channels for other tasks (such as camera switching), but it will be another feature that only a few people use and that confuses them when first setting up to system. So don't get your hopes up too much.
DroneBridge RC should offer a lot more range than the Video link since it is transmitted on lower bitrates. You will need to have a very good/expensive RC to be able to beat DroneBridge RCs range (I know DragonLink can do that ;) ).

I will take a look at your code and think about how to integrate it. If it does not make it into the image in the way you want/need it you could craft some sort of plugin that other people can download and use if they need that exact same functionality. No matter what, thank you for contributing!

**Comment by careyer** [comment]
Hi there,

es far as I could find out Graupner SUMD is only supported via PX4 stack on Pixracer. Ardupilot only supports SBUS. 
Correct me if I am wrong but: even if SUMD would work somehow one would loose MavLink telemetry since the AirPi' s serial port is occupied, right?

Cheers


Von meinem iPhone gesendet

**Comment by seeul8er** [comment]
[According to this doc SUMD is supported.](http://ardupilot.org/copter/docs/common-pixracer-overview.html#rc-input-accepts-ppm-s-bus-spektrum-sumd-st24)

The thing with the serial port is true. You will need to use an extra FTDI adapter to get a second UART. But that would be the same if you had any other protocol. "Bit banging some other GPIOs" would just cause too much extra load on the CPU. So for MAVLink based FCs it is always: Extra FTDI or separate RC link directly connected to the FC.

**Comment by careyer** [comment]
Oh wow... SUMD support must be newly supported. Thanks for the link. However loosing telemetry in exchange for some more channels does not make sense either. 

I assume With "Bit banging some other GPIOs" you mean simulating another serial port or outputting PWM signals via GPIO, right? But it would not be too much CPU load to add some switchable outputs like On/Off I suppose. For most additional applications you do not really need proportional channels (0-1023) but just On/ Off - e.g. landing gear, lights, drop hook, etc.

Best regards 


Von meinem iPhone gesendet

**Comment by htcohio** [comment]
@careyer hey, that case enclosure on the back of the transmitter is really neat.  Does it have SMA connectors on the top side?

I would be interested in having that on the back of mine, do you have the 3D print file by chance? A buddy of mine has a printer and can print it for me.

**Comment by careyer** [comment]
@htcohio : The case is CNC milled from a solid block of aluminum and serves at the same time as a heatsink for the RPi3 and both TP-Link 722N Sticks. Every IC inside has direct connection via thermal paste to the housing and yes it has 2 SMA connectors. Since a friend magically CNC-ed this somehow I have no files. For the AirPi we use a similar construction... also a full aluminum enclosure for the Pi0 and the Alfa 036NHA. Works pretty well. Temperatures are decreased from about 75°C to 35°C

**Comment by htcohio** [comment]
Hey, I actually picked up a CNC router last year and I upgraded it to a 2KW spindle motor which can handle aluminum no problem.

I also have a couple of nice blocks of aluminum I've been holding onto so this could be the perfect time to try it.

I'll try putting a design together tonight

**Comment by careyer** [comment]
Haha... Happy that i could inspire you. :-).
My friend is a wizard when it comes to CNCing. It is like magic what he does to raw aluminum. The damn thing is milled from 4 sides and snuggly fits a Rpi3 in place. I have no idea how long it took him to make this thing but it is worth the effort.

Von meinem iPhone gesendet

**Comment by seeul8er** [comment]
With v0.5 you should now be able to trigger a camera switch via the app. In the upper left corner, you find a drop-down spinner. I was not able to test it since I do not have the hardware. [The implementation can be found here](https://github.com/seeul8er/DroneBridge/blob/master/communication/db_comm_messages.py#L259).

You can test it if you like.

**Comment by seeul8er** [comment]
[Please comment in custom action issue](https://github.com/seeul8er/DroneBridge/issues/18) for any further discussion on ON/OFF channels

**Comment by seeul8er** [comment]
@htcohio  Can you please clarify what exactly is not working with the camera switch?
Is it not working at all?
Does it only make problems when outputs without a camera are selected?

**Comment by htcohio** [comment]
The camera switch was originally set up and worked by monitoring Channel 7 (or any other defined control Channel). 

The camera switcher is also capable of 4 cameras which need to be defined as active or inactive as well as pwm values in order to trigger the respective cameras.

I don't know anything about coding and user 1321 reached out to me a few months ago after I posted a request for someone to help get the video switch working.  I think he identified where the problem was on drone Bridge but you'll have to get with him on that.

I am attaching a Dropbox link to the most recent wifibroadcast image the contains the working code for the video switch. Being able to use it in your app would be nice but I will primarily use it with RC Ch7 & 3 pos. switch. It also contains other code for a gpio 21 button to enable or disable the hot spot on and a modified version of the fpv VR app whose main purpose was being able to change the video and FEC settings through the fpvvr app, I think that part can be disregarded though.

I also attached a screenshot for how the settings were laid out, let me know if you're able to see it

Great work so far though! Let me know if you have any questions

https://www.dropbox.com/sh/3iyg7ks7mmci7lo/AABXMycj6fz0F5e-LLXQp0Qaa?dl=0

![EZ WiFi broadcast Arducam multi camera board]()

**Comment by htcohio** [comment]
Hey, which Android app is the correct one right now for testing some of the recent changes? 1.2.3 the beta version appears to look the same as the one I already used, however the 1. 2. 2 is giving me the beta disclosure on the initial start.

Is that one supposed to be 1. 2. 3?

Thanks!

**Comment by seeul8er** [comment]
> Hey, which Android app is the correct one right now for testing some of the recent changes? 1.2.3 the beta version appears to look the same as the one I already used, however the 1. 2. 2 is giving me the beta disclosure on the initial start.

Always go with the latest version. Changes might not always be visible to the user.

**Comment by htcohio** [comment]
Hello,

I completed some testing of 0.6 tonight and I do not have the video switch control.

The working image has already been submitted to you and you'll notice there is a new "Camcontrol.txt" file that was added to that image where the number of cameras (cam1-4) can be defined as well as the RC Channel number and corresponding pwm values.

User1321 would be the one to answer any questions

**Comment by seeul8er** [comment]
postponed
