### ISSUE TITLE
Is this project no longer under maintenance?

### ISSUE THREAD

**Issue by cgrrty** [DroneBridge/DroneBridge#69]
Is this project no longer under maintenance?

**Comment by CopterGUI** [comment]
Seems to be the toy-project of a single person.

If you are looking for something similar that works, use OpenHD, it's much better.

**Comment by cgrrty** [comment]
I think this is more standardized than openhd's code, and it's more suitable for people who want to learn programming.

**Comment by CopterGUI** [comment]
Why do you think that?
Because you read it in the dronekit wiki ?

**Comment by seeul8er** [comment]
@CopterGUI please do not promote here. Seems like there is still enough interesting content to learn from to keep lingering around the repo.
@cgrrty I am the only active developer right now. Development is halted since I am trying to get my 3D printed drone hardware ready. I spent so much time developing DroneBridge that I never managed getting the hardware running. That will still take a few weeks, after that I will fix some issues here.
I do not know anything about the latest releases of OpenHD. Their docs are still lacking a lot. Looking at the lastest code it looks like they finally rewrote much of it. This is just as much "toy-project" as OpenHD. In fact much of the new stuff that OpenHD is doing now (app, library, docs, rewrite of WBC code, logo etc.) was done with DroneBridge 3 years ago. In my opinion DroneBridge is still cleaner and more modular. The docs are also better. Latest hardware might be better supported by OpenHD. I'd argue that none of the projects are simple and thus easy to understand for beginners.

**Comment by CopterGUI** [comment]
Hello @seeul8er 
This was not not meant as promotion. I'm just a drone enthusiast and user of all of these project's. 
Not a developer. 
What made me angry is that your wiki is very misleading to new users. It hard to gather information as a newcomer and people will believe what they read there.
And I'm not lingering around your repo, that's the new GitHub app that sends me tons of notifications, I try to turn it off and will not disturb you any longer.

Anyway my choice of words was unnecessary harsh and I want to apologize for that.

**Comment by cgrrty** [comment]
@seeul8er thank you
