### ISSUE TITLE
How does this work ? The docs are useless.

### ISSUE THREAD

**Issue by GeorgeFlorian** [DroneBridge/DroneBridge#75]
I am trying to make this project work, but I have no idea how.
The guides are useless and have 0 information.

Do I connect the Raspberry to a network ? What if I want to, how can I do that then ?
Why do I need WiFi sticks ? Does the RPI needs to be connected to an Wireless Network ?
What if I want to use an Ethernet cable ?
How do I tell one Raspberry that it is Air and the other one that it is Ground ? Both [AIR] and [GROUND] are defined in the v0.7 image.

I have the following inside `DroneBridgeConfig.ini` to maybe make one Raspberry be Air
```
[GROUND]
en_control=N
en_video=N
en_comm=N
en_plugin=N
```

I am only trying to test things so I have powerd the RPI using an USB cable. I have also hooked an HDMI cable to it but there is no signal.
Also, the softAP doesn't work, as there is no network to connect to when the Raspberry is running. These are the settings regarding the softAP:
```
wifi_ap=Y
wifi_ap_if=internal
```

I don't have WiFi Stick, so how can I test this project ? Can I tell the RPI to connect to my Wireless network ? How ?

**Comment by seeul8er** [comment]
You clearly do not understand what this project is and what it does. Maybe this is not for you. Instead of reading about wifibroadcast and the wiki etc. you go straight to the issue section on Github to share your ignorance. This is an open source project (even the wiki is) so feel free to contribute if you think something is not correct.

So to make this quick: 
- The air-side is identified by a connected RPi Camera module (yes - that is not in the wiki - sorry about that)
- You can connect the Pi to a network by connecting the ethernet network port of the Pi to your network
- No you can not test it without wifi sticks. How tf would you send and receive data then?
- DroneBridge for RPi is not using Wifi! Only Wifi hardware.
- And yes the code is pretty old and at some point there are bugs that need fixes, but since I have no time left to invest right now this has to wait till someone else fixes it or I find time to get back behind my own drone project.
